// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pejdivbehjworooeiuao.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlamRpdmJlaGp3b3Jvb2VpdWFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg3NTY5MDgsImV4cCI6MjA1NDMzMjkwOH0.ltdnxqz7Hf5dtfM_OWWZ4JQgUl1vbKuxE2kJ1jw54ng";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);